### PR TITLE
Add SRC support for SAT>IP

### PR DESCRIPTION
**Pull request by lars18th**
Pass the SRC parameter to the SAT>IP server using the DiseqC value from the parameter "-D". All values for committed and uncommitted are valid.

### CODE REVIEW

**Comment by lars18th** [comment]
This fixes the issue #11

**Comment by wirbel-at-vdr-portal** [comment]
The SAT>IP spec says..

```
Name          | Attribute | Value-Name | Value-Range                       | Example
--------------+-----------+------------+-----------------------------------+----------
Signal source | src       | srcID      | Numerical value between 1 and 255.| src=1
```

`The source parameter communicates to the frontend the selection of a satellite orbital position.`

This solution uses a variable called 'DiseqcSwitch', which is wrong.

DiSEqC is here only _one of several possibilities_, the client just chooses an _orbital position_ by number.

Furthermore in SAT>IP spec..
```
Multiswitch servers implementing DiSEqC shall always map the source parameter as follows:
“src”        DiSEqC
  1          DiSEqC A = Position A Option A
  2          DiSEqC B = Position B Option A
  3          DiSEqC C = Position A Option B
  4          DiSEqC D = Position B Option B
```
There is written 'shall', bot not 'must': no fixed order on them. Just a recommendation.

For w_scan_cpp this is a command send by hardware and therefore fixed order, relating to 0..3. 



This patch also allows the selection of zero, using 0c or 0u.

From the satip Plugin README:
_A special number zero can be used to disable the source._
This is certainly not what was intended, disabling the source to be scanned.

As DiSEqC numeration goes from 0..3 or 0..15 and SAT>IP from 1..255, this approach of using -D option looks wrong to me.

Also, activating diseqc switches creates a table of diseqc commands which will be printed on cmdline, but never used. And the diseqc option of VDR is activated.

All of this looks like a bunch of new problems, if using this approach.

**Comment by wirbel-at-vdr-portal** [comment]
Hi lars18th,

i added just now a new commandline switch --satip-src to main.

**Comment by wirbel-at-vdr-portal** [comment]
I would like to close soon, if you don't have further issues here.

**Comment by wirbel-at-vdr-portal** [comment]
I'm closing, as no more activity is here. Feel free to re-open, if it doesn't work.

**Pull request closed without merging**
