### PR TITLE
Add all pids of the service with SAT>IP

### PR DESCRIPTION
**Pull request by lars18th**
This patch adds all pids of the service in the XSPF output when using SAT>IP.

### CODE REVIEW

**Comment by wirbel-at-vdr-portal** [comment]
Why ...

     if (c.APIDs.Count() > 0) for (int i=0; i < c.APIDs.Count(); i++)
                              ss << ',' << c.APIDs[i].PID;

instead of ...

     for(int i=0; i<c.APIDs.Count(); i++)
        ss << ',' << c.APIDs[i].PID;

?

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

I have polished all the code. And included all the mandatory descriptions. IMHO it's ready to merge.
You agree?

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

Sorry for a lot of commits just for the wrong merge fix. Now it's ready to commit. However, I suggest to squash to generate only one commit merge.

**Comment by wirbel-at-vdr-portal** [comment]
Agree, ready now.

**Pull request merged**
